-- ============================================================================
-- DELTA PROSPECT SYSTEM v2.0 — Database Schema
-- PostgreSQL 15+
-- ============================================================================
-- New Delta 6-Pillar alignment:
--   Production, License to Operate, Cost, People, Quality, Future Readiness
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- ============================================================================
-- MIGRATION: Replace old 7-category pressure_type with 6-pillar version
-- ============================================================================
-- Safe to run on fresh databases (no-ops) and existing databases (wipes
-- old signal data which will be regenerated by the new enrichment engine).

DO $$ BEGIN
    -- If the old enum exists with old values, drop signals + enum so we can recreate
    IF EXISTS (
        SELECT 1 FROM pg_type t
        JOIN pg_enum e ON e.enumtypid = t.oid
        WHERE t.typname = 'pressure_type' AND e.enumlabel = 'operational'
    ) THEN
        -- Drop views that depend on pressure_type column first
        DROP VIEW IF EXISTS v_prospect_dashboard CASCADE;
        DROP VIEW IF EXISTS v_sector_summary CASCADE;
        -- Wipe old signal data (safe — will be re-enriched with new pillars)
        TRUNCATE pressure_signals;
        -- Drop the column and enum with CASCADE to clear all dependencies
        ALTER TABLE pressure_signals DROP COLUMN IF EXISTS pressure_type CASCADE;
        DROP TYPE IF EXISTS pressure_type CASCADE;
        RAISE NOTICE 'Migration: dropped old pressure_type enum and cleared signal data';
    END IF;
EXCEPTION
    WHEN undefined_table THEN NULL;  -- pressure_signals doesn't exist yet
    WHEN undefined_object THEN NULL; -- pressure_type doesn't exist yet
END $$;

-- Add lead_tier column if table already exists (for existing databases)
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'prospect_matrix') THEN
        ALTER TABLE prospect_matrix ADD COLUMN IF NOT EXISTS lead_tier VARCHAR(20) DEFAULT 'not_qualified';
        ALTER TABLE prospect_matrix ADD COLUMN IF NOT EXISTS is_watchlisted BOOLEAN DEFAULT FALSE;
    END IF;
END $$;

-- v2.1 migration: accessibility_score, size_of_prize, prize_breakdown
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'prospect_matrix') THEN
        ALTER TABLE prospect_matrix ADD COLUMN IF NOT EXISTS accessibility_score INTEGER DEFAULT 5;
        ALTER TABLE prospect_matrix ADD COLUMN IF NOT EXISTS size_of_prize BIGINT;
        ALTER TABLE prospect_matrix ADD COLUMN IF NOT EXISTS prize_breakdown JSONB;
    END IF;
END $$;

-- v2.2 migration: replace accessibility_score with text location fields;
--                 add deep analysis extended output columns
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'prospect_matrix') THEN
        -- Drop the numeric score; replaced by text location fields
        ALTER TABLE prospect_matrix DROP COLUMN IF EXISTS accessibility_score;
        -- Location fields
        ALTER TABLE prospect_matrix ADD COLUMN IF NOT EXISTS registered_city  TEXT;
        ALTER TABLE prospect_matrix ADD COLUMN IF NOT EXISTS registered_state TEXT;
        ALTER TABLE prospect_matrix ADD COLUMN IF NOT EXISTS in_australia      BOOLEAN DEFAULT TRUE;
        -- Deep analysis extended output
        ALTER TABLE prospect_matrix ADD COLUMN IF NOT EXISTS key_pressures      TEXT;
        ALTER TABLE prospect_matrix ADD COLUMN IF NOT EXISTS nd_fit_assessment  TEXT;
        ALTER TABLE prospect_matrix ADD COLUMN IF NOT EXISTS prize_ai_assessment TEXT;
        ALTER TABLE prospect_matrix ADD COLUMN IF NOT EXISTS outreach_hypothesis TEXT;
        ALTER TABLE prospect_matrix ADD COLUMN IF NOT EXISTS red_flags           TEXT;
    END IF;
END $$;

-- ============================================================================
-- ENUMS
-- ============================================================================

DO $$ BEGIN
    CREATE TYPE prospect_status AS ENUM (
        'unscreened',
        'qualified',
        'enriched',
        'ready_for_outreach',
        'suggested_dq',
        'disqualified',
        'archived'
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE enrichment_source AS ENUM (
        'asx_announcement',
        'annual_report',
        'quarterly_report',
        'investor_presentation',
        'media_article',
        'manual_entry'
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE pressure_type AS ENUM (
        'production',
        'license_to_operate',
        'cost',
        'people',
        'quality',
        'future_readiness'
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE signal_strength AS ENUM (
        'weak',
        'moderate',
        'strong'
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ============================================================================
-- CORE TABLES
-- ============================================================================

-- Master list: every ASX-listed entity, refreshed weekly from the CSV feed
CREATE TABLE IF NOT EXISTS asx_listings (
    id                   UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    ticker               VARCHAR(10) NOT NULL,
    company_name         TEXT NOT NULL,
    gics_industry_group  TEXT,
    gics_sector          TEXT,
    is_target_sector     BOOLEAN DEFAULT FALSE,
    listing_date         DATE,
    market_cap_aud       BIGINT,          -- cents (avoids float drift)
    last_price_aud       INTEGER,         -- cents
    website              TEXT,
    principal_activities TEXT,
    first_seen_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_refreshed_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    is_active            BOOLEAN DEFAULT TRUE,
    delisted_at          TIMESTAMPTZ,
    CONSTRAINT uq_ticker UNIQUE (ticker)
);

CREATE INDEX IF NOT EXISTS idx_listings_target   ON asx_listings (is_target_sector) WHERE is_active = TRUE;
CREATE INDEX IF NOT EXISTS idx_listings_sector   ON asx_listings (gics_sector)      WHERE is_active = TRUE;
CREATE INDEX IF NOT EXISTS idx_listings_ticker   ON asx_listings (ticker);
CREATE INDEX IF NOT EXISTS idx_listings_name_trg ON asx_listings USING gin (company_name gin_trgm_ops);

-- ============================================================================
-- PROSPECT MATRIX — the filtered, scored, working set
-- ============================================================================

CREATE TABLE IF NOT EXISTS prospect_matrix (
    id                       UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    listing_id               UUID NOT NULL REFERENCES asx_listings(id) ON DELETE CASCADE,
    status                   prospect_status NOT NULL DEFAULT 'unscreened',
    status_changed_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    status_changed_by        TEXT,
    dq_reason                TEXT,

    -- Strategic profile (populated by enrichment agent)
    strategic_direction      TEXT,
    primary_tailwind         TEXT,
    primary_headwind         TEXT,
    likelihood_score         SMALLINT CHECK (likelihood_score BETWEEN 1 AND 10),

    -- Composite score
    prospect_score           NUMERIC(5,2),
    score_updated_at         TIMESTAMPTZ,

    -- Lead classification
    lead_tier                VARCHAR(20) DEFAULT 'not_qualified',

    -- Buyer identification
    primary_buyer_name       TEXT,
    primary_buyer_role       TEXT,
    primary_buyer_linkedin   TEXT,
    secondary_buyer_name     TEXT,
    secondary_buyer_role     TEXT,
    secondary_buyer_linkedin TEXT,

    -- Network intelligence
    network_path             TEXT,
    warm_intro_contact       TEXT,

    analyst_notes            TEXT,
    is_watchlisted           BOOLEAN DEFAULT FALSE,

    -- v2.1: Size of Prize
    size_of_prize            BIGINT,
    prize_breakdown          JSONB,

    -- v2.2: Location fields (from principal_activities text detection)
    registered_city          TEXT,
    registered_state         TEXT,
    in_australia             BOOLEAN DEFAULT TRUE,

    -- v2.2: Deep analysis extended output
    key_pressures            TEXT,
    nd_fit_assessment        TEXT,
    prize_ai_assessment      TEXT,
    outreach_hypothesis      TEXT,
    red_flags                TEXT,

    created_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_listing_prospect UNIQUE (listing_id)
);

CREATE INDEX IF NOT EXISTS idx_prospect_status ON prospect_matrix (status);
CREATE INDEX IF NOT EXISTS idx_prospect_score  ON prospect_matrix (prospect_score DESC NULLS LAST);
CREATE INDEX IF NOT EXISTS idx_prospect_tier   ON prospect_matrix (lead_tier);

-- ============================================================================
-- PRESSURE SIGNALS — the core intelligence layer (6-pillar model)
-- ============================================================================

CREATE TABLE IF NOT EXISTS pressure_signals (
    id               UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    prospect_id      UUID NOT NULL REFERENCES prospect_matrix(id) ON DELETE CASCADE,
    pressure_type    pressure_type NOT NULL,
    strength         signal_strength NOT NULL DEFAULT 'moderate',
    summary          TEXT NOT NULL,
    source_type      enrichment_source NOT NULL,
    source_url       TEXT,
    source_title     TEXT,
    source_date      DATE,
    extracted_quote  TEXT,
    confidence_score NUMERIC(3,2) CHECK (confidence_score BETWEEN 0 AND 1),
    model_version    TEXT,
    detected_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    validated_by     TEXT,
    validated_at     TIMESTAMPTZ,
    is_valid         BOOLEAN,
    CONSTRAINT uq_signal_source UNIQUE (prospect_id, pressure_type, source_url)
);

-- Re-add the pressure_type column if the migration dropped it
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'pressure_signals' AND column_name = 'pressure_type'
    ) THEN
        ALTER TABLE pressure_signals ADD COLUMN pressure_type pressure_type NOT NULL DEFAULT 'production';
    END IF;
END $$;

-- Re-add unique constraint if the migration dropped it
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'pressure_signals'::regclass AND conname = 'uq_signal_source'
    ) THEN
        ALTER TABLE pressure_signals ADD CONSTRAINT uq_signal_source UNIQUE (prospect_id, pressure_type, source_url);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_signals_prospect ON pressure_signals (prospect_id);
CREATE INDEX IF NOT EXISTS idx_signals_type     ON pressure_signals (pressure_type);
CREATE INDEX IF NOT EXISTS idx_signals_strength ON pressure_signals (strength);

-- ============================================================================
-- ENRICHMENT LOG — audit trail
-- ============================================================================

CREATE TABLE IF NOT EXISTS enrichment_log (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    listing_id          UUID NOT NULL REFERENCES asx_listings(id) ON DELETE CASCADE,
    action              TEXT NOT NULL,
    source_type         enrichment_source,
    source_url          TEXT,
    success             BOOLEAN NOT NULL,
    error_message       TEXT,
    documents_processed INTEGER DEFAULT 0,
    signals_found       INTEGER DEFAULT 0,
    started_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at        TIMESTAMPTZ,
    duration_ms         INTEGER,
    tokens_used         INTEGER,
    triggered_by        TEXT NOT NULL DEFAULT 'system',
    agent_version       TEXT
);

CREATE INDEX IF NOT EXISTS idx_enrich_listing ON enrichment_log (listing_id);
CREATE INDEX IF NOT EXISTS idx_enrich_started ON enrichment_log (started_at DESC);

-- ============================================================================
-- GICS SECTOR MAP — reference table for sector filtering
-- ============================================================================

CREATE TABLE IF NOT EXISTS gics_sector_map (
    industry_group TEXT PRIMARY KEY,
    gics_sector    TEXT NOT NULL,
    is_target      BOOLEAN NOT NULL DEFAULT FALSE,
    notes          TEXT
);

INSERT INTO gics_sector_map (industry_group, gics_sector, is_target, notes) VALUES
    ('Energy',                                        'Energy',                 TRUE,  'Oil, gas, consumable fuels, energy equipment & services'),
    ('Materials',                                     'Materials',              TRUE,  'Metals & mining, chemicals, construction materials'),
    ('Capital Goods',                                 'Industrials',            TRUE,  'Aerospace, building products, construction & engineering, machinery'),
    ('Utilities',                                     'Utilities',              TRUE,  'Electric, gas, water utilities; renewable energy'),
    ('Commercial & Professional Services',            'Industrials',            FALSE, NULL),
    ('Transportation',                                'Industrials',            FALSE, NULL),
    ('Automobiles & Components',                      'Consumer Discretionary', FALSE, NULL),
    ('Consumer Discretionary Distribution & Retail',  'Consumer Discretionary', FALSE, NULL),
    ('Consumer Durables & Apparel',                   'Consumer Discretionary', FALSE, NULL),
    ('Consumer Services',                             'Consumer Discretionary', FALSE, NULL),
    ('Media & Entertainment',                         'Communication Services', FALSE, NULL),
    ('Telecommunication Services',                    'Communication Services', FALSE, NULL),
    ('Consumer Staples Distribution & Retail',        'Consumer Staples',       FALSE, NULL),
    ('Food, Beverage & Tobacco',                      'Consumer Staples',       FALSE, NULL),
    ('Household & Personal Products',                 'Consumer Staples',       FALSE, NULL),
    ('Banks',                                         'Financials',             FALSE, NULL),
    ('Diversified Financials',                        'Financials',             FALSE, NULL),
    ('Financial Services',                            'Financials',             FALSE, NULL),
    ('Insurance',                                     'Financials',             FALSE, NULL),
    ('Health Care Equipment & Services',              'Health Care',            FALSE, NULL),
    ('Pharmaceuticals, Biotechnology & Life Sciences','Health Care',            FALSE, NULL),
    ('Software & Services',                           'Information Technology', FALSE, NULL),
    ('Technology Hardware & Equipment',               'Information Technology', FALSE, NULL),
    ('Semiconductors & Semiconductor Equipment',      'Information Technology', FALSE, NULL),
    ('Equity Real Estate Investment Trusts (REITs)',  'Real Estate',            FALSE, NULL),
    ('Real Estate Management & Development',          'Real Estate',            FALSE, NULL),
    ('Not Applic',                                    'Other',                  FALSE, 'ETFs, LICs, trusts')
ON CONFLICT (industry_group) DO UPDATE SET
    gics_sector = EXCLUDED.gics_sector,
    is_target   = EXCLUDED.is_target,
    notes       = EXCLUDED.notes;

-- ============================================================================
-- REFRESH RUNS — tracks weekly + on-demand refresh cycles
-- ============================================================================

CREATE TABLE IF NOT EXISTS refresh_runs (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    run_type            TEXT NOT NULL CHECK (run_type IN ('weekly','manual','on_demand_single')),
    total_listings      INTEGER,
    new_listings        INTEGER DEFAULT 0,
    updated_listings    INTEGER DEFAULT 0,
    delisted_count      INTEGER DEFAULT 0,
    target_sector_count INTEGER DEFAULT 0,
    status              TEXT NOT NULL DEFAULT 'running' CHECK (status IN ('running','completed','failed')),
    error_message       TEXT,
    started_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at        TIMESTAMPTZ,
    triggered_by        TEXT NOT NULL DEFAULT 'system'
);

CREATE INDEX IF NOT EXISTS idx_refresh_started ON refresh_runs (started_at DESC);

-- ============================================================================
-- TRIGGERS
-- ============================================================================

CREATE OR REPLACE FUNCTION update_prospect_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    IF OLD.status IS DISTINCT FROM NEW.status THEN
        NEW.status_changed_at = NOW();
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$ BEGIN
    CREATE TRIGGER trg_prospect_updated
        BEFORE UPDATE ON prospect_matrix
        FOR EACH ROW EXECUTE FUNCTION update_prospect_timestamp();
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ============================================================================
-- SCORING FUNCTION — New Delta 6-Pillar Weighted Model
-- ============================================================================
-- score = Σ(strength_weight × pillar_weight) × likelihood / 10
--   strength:  strong=3, moderate=2, weak=1
--   pillar weights (normalized to sum to ~1.0):
--     production=0.40, license_to_operate=0.20, cost=0.15,
--     people=0.15, quality=0.05, future_readiness=0.05

CREATE OR REPLACE FUNCTION calculate_prospect_score(p_prospect_id UUID)
RETURNS NUMERIC AS $$
DECLARE
    signal_score NUMERIC;
    likelihood   SMALLINT;
    final_score  NUMERIC;
BEGIN
    SELECT COALESCE(SUM(
        CASE strength WHEN 'strong' THEN 3.0 WHEN 'moderate' THEN 2.0 WHEN 'weak' THEN 1.0 END
        *
        CASE pressure_type
            WHEN 'production'          THEN 4.0
            WHEN 'license_to_operate'  THEN 2.0
            WHEN 'cost'                THEN 1.5
            WHEN 'people'              THEN 1.5
            WHEN 'quality'             THEN 0.5
            WHEN 'future_readiness'    THEN 0.5
        END
    ), 0) INTO signal_score
    FROM pressure_signals
    WHERE prospect_id = p_prospect_id
      AND (is_valid IS NULL OR is_valid = TRUE);

    SELECT pm.likelihood_score INTO likelihood
    FROM prospect_matrix pm WHERE pm.id = p_prospect_id;

    final_score := signal_score * COALESCE(likelihood, 5) / 10.0;

    UPDATE prospect_matrix
    SET prospect_score = final_score, score_updated_at = NOW()
    WHERE id = p_prospect_id;

    RETURN final_score;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- LEAD TIER CALCULATION FUNCTION
-- ============================================================================
-- Hot:  3+ pillars with at least one strong signal each
-- Warm: 1-2 pillars with strong signals, OR 3+ pillars with moderate+ signals
-- Watch: Signals present but weak or limited to 1 pillar
-- Not Qualified: No signals

CREATE OR REPLACE FUNCTION calculate_lead_tier(p_prospect_id UUID)
RETURNS VARCHAR AS $$
DECLARE
    total_signals     INTEGER;
    pillars_strong    INTEGER;  -- pillars that have at least one strong signal
    pillars_moderate  INTEGER;  -- pillars that have at least one moderate+ signal
    tier              VARCHAR(20);
BEGIN
    SELECT COUNT(*) INTO total_signals
    FROM pressure_signals
    WHERE prospect_id = p_prospect_id AND (is_valid IS NULL OR is_valid = TRUE);

    SELECT COUNT(DISTINCT pressure_type) INTO pillars_strong
    FROM pressure_signals
    WHERE prospect_id = p_prospect_id AND strength = 'strong'
      AND (is_valid IS NULL OR is_valid = TRUE);

    SELECT COUNT(DISTINCT pressure_type) INTO pillars_moderate
    FROM pressure_signals
    WHERE prospect_id = p_prospect_id AND strength IN ('strong', 'moderate')
      AND (is_valid IS NULL OR is_valid = TRUE);

    IF total_signals = 0 THEN
        tier := 'not_qualified';
    ELSIF pillars_strong >= 3 THEN
        tier := 'hot';
    ELSIF pillars_strong >= 1 OR pillars_moderate >= 3 THEN
        tier := 'warm';
    ELSE
        tier := 'watch';
    END IF;

    UPDATE prospect_matrix SET lead_tier = tier WHERE id = p_prospect_id;
    RETURN tier;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- VIEWS
-- ============================================================================

CREATE OR REPLACE VIEW v_prospect_dashboard AS
SELECT
    pm.id AS prospect_id, l.ticker, l.company_name, l.gics_sector,
    l.gics_industry_group, l.market_cap_aud, l.last_price_aud, l.website,
    pm.status, pm.prospect_score, pm.lead_tier, pm.strategic_direction,
    pm.primary_tailwind, pm.primary_headwind, pm.likelihood_score,
    pm.primary_buyer_name, pm.primary_buyer_role, pm.network_path,
    pm.analyst_notes, pm.updated_at, pm.is_watchlisted,
    COUNT(ps.id) AS total_signals,
    COUNT(ps.id) FILTER (WHERE ps.strength = 'strong') AS strong_signals,
    COUNT(ps.id) FILTER (WHERE ps.is_valid = TRUE)     AS validated_signals,
    COUNT(ps.id) FILTER (WHERE ps.pressure_type = 'production')         AS sig_production,
    COUNT(ps.id) FILTER (WHERE ps.pressure_type = 'license_to_operate') AS sig_license,
    COUNT(ps.id) FILTER (WHERE ps.pressure_type = 'cost')               AS sig_cost,
    COUNT(ps.id) FILTER (WHERE ps.pressure_type = 'people')             AS sig_people,
    COUNT(ps.id) FILTER (WHERE ps.pressure_type = 'quality')            AS sig_quality,
    COUNT(ps.id) FILTER (WHERE ps.pressure_type = 'future_readiness')   AS sig_future,
    MAX(ps.source_date) AS latest_signal_date
FROM prospect_matrix pm
JOIN asx_listings l ON l.id = pm.listing_id
LEFT JOIN pressure_signals ps ON ps.prospect_id = pm.id
WHERE l.is_active = TRUE
GROUP BY pm.id, l.id;

CREATE OR REPLACE VIEW v_sector_summary AS
SELECT
    l.gics_sector, l.gics_industry_group,
    COUNT(*) AS total_companies,
    COUNT(pm.id) AS in_matrix,
    COUNT(pm.id) FILTER (WHERE pm.status = 'qualified')          AS qualified,
    COUNT(pm.id) FILTER (WHERE pm.status = 'enriched')           AS enriched,
    COUNT(pm.id) FILTER (WHERE pm.status = 'ready_for_outreach') AS ready_for_outreach,
    AVG(pm.prospect_score) AS avg_score
FROM asx_listings l
LEFT JOIN prospect_matrix pm ON pm.listing_id = l.id
WHERE l.is_target_sector = TRUE AND l.is_active = TRUE
GROUP BY l.gics_sector, l.gics_industry_group
ORDER BY total_companies DESC;

-- ============================================================================
-- TABLE COMMENTS
-- ============================================================================

COMMENT ON TABLE asx_listings      IS 'Master list of all ASX-listed entities. Source: asx.com.au/asx/research/ASXListedCompanies.csv';
COMMENT ON TABLE prospect_matrix   IS 'Filtered/scored subset in target sectors. Core working table.';
COMMENT ON TABLE pressure_signals  IS 'Pressure signals extracted from public filings — 6-pillar model (Production, License to Operate, Cost, People, Quality, Future Readiness).';
COMMENT ON TABLE enrichment_log    IS 'Audit trail for all automated data pulls and analysis runs.';
COMMENT ON TABLE gics_sector_map   IS 'Reference mapping: ASX GICS industry groups → sectors & target classification.';
COMMENT ON TABLE refresh_runs      IS 'Tracks weekly and on-demand data refresh cycles.';
